// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkHpcfoxEZSvmFRKGwUwuO1LnmihUdGfU',
    appId: '1:732129842851:web:7b0bc8e041b6e2ae645116',
    messagingSenderId: '732129842851',
    projectId: 'jon-sport',
    authDomain: 'jon-sport.firebaseapp.com',
    storageBucket: 'jon-sport.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFJm0DQyoJT-TK-aZGRHK9duw2izZbYOU',
    appId: '1:732129842851:android:9629ed8f4c988190645116',
    messagingSenderId: '732129842851',
    projectId: 'jon-sport',
    storageBucket: 'jon-sport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMiQc3TLsK88sLlPoQck2xxBMNUxA5lSA',
    appId: '1:732129842851:ios:188ba17e1684c6bb645116',
    messagingSenderId: '732129842851',
    projectId: 'jon-sport',
    storageBucket: 'jon-sport.firebasestorage.app',
    iosBundleId: 'com.jonsport.businessDashboard',
  );
}
