#!/usr/bin/env bash
# Local Chrome on fixed port 8080 + optional dev Firebase API key (no GCP referrer issues).
set -euo pipefail
cd "$(dirname "$0")/.."

if lsof -ti:8080 >/dev/null 2>&1; then
  echo "Port 8080 in use — stopping existing process..."
  lsof -ti:8080 | xargs kill -9 2>/dev/null || true
  sleep 1
fi

ARGS=(run -d chrome --web-port=8080 --web-hostname=localhost)

if [[ -f env/dev.json ]]; then
  if grep -q 'PASTE_DEV_API_KEY_HERE' env/dev.json 2>/dev/null; then
    echo "ERROR: Edit env/dev.json — replace PASTE_DEV_API_KEY_HERE with your dev API key."
    exit 1
  fi
  DEV_KEY="$(python3 -c "import json; print(json.load(open('env/dev.json'))['FIREBASE_WEB_API_KEY'])" 2>/dev/null || true)"
  if [[ -z "$DEV_KEY" ]]; then
    echo "ERROR: env/dev.json must contain FIREBASE_WEB_API_KEY"
    exit 1
  fi
  cat > web/firebase_dev_config.js <<EOF
// Auto-generated by tool/dev_run_chrome.sh from env/dev.json
window.__BINISOFT_FIREBASE_API_KEY = '$DEV_KEY';
EOF
  ARGS+=(--dart-define-from-file=env/dev.json)
  echo "✓ Using env/dev.json (dev API key …${DEV_KEY: -6}). Network tab must NOT show …UdGfU."
elif [[ -n "${FIREBASE_WEB_API_KEY:-}" ]]; then
  ARGS+=(--dart-define="FIREBASE_WEB_API_KEY=${FIREBASE_WEB_API_KEY}")
  echo "✓ Using FIREBASE_WEB_API_KEY from shell."
else
  echo ""
  echo "⚠️  No dev API key — login will 403 on localhost until you:"
  echo "   1. GCP → Create API key → Application restrictions: None"
  echo "   2. cp env/dev.json.example env/dev.json"
  echo "   3. Paste the new key into env/dev.json"
  echo ""
  echo "   Prod key (github.io) stays restricted; dev key is only for local."
  echo ""
fi

echo "→ http://localhost:8080/#/login"
flutter "${ARGS[@]}"
